module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  auditfiles: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  build_hooks: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  consumers: 0
  contact: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  entity_usage: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  gin_toolbar: 0
  graphql: 0
  graphql_core: 0
  graphql_metatag: 0
  graphql_views: 0
  help: 0
  history: 0
  image: 0
  inline_entity_form: 0
  link: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  node: 0
  options: 0
  page_cache: 0
  paragraphs_edit: 0
  paragraphs_library: 0
  path: 0
  path_alias: 0
  quickedit: 0
  rdf: 0
  redirect: 0
  search: 0
  serialization: 0
  shortcut: 0
  simple_oauth: 0
  site_settings: 0
  subpathauto: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_ui: 0
  pathauto: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  claro: 0
  gin: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
